[reddit]
client_id = "ChEVxaOTP3KVXsQWJBVp7Q"
client_secret = "z5xLjlEiRmX6JEpem_UxQus0hqwmpQ"
user_agent = "CoffeePulse by Many_Marketing1359"
username = "Many_Marketing1359"
password = "2%)jw:6.)v%utP<"

